title: Senobessus Dexoarês
email: sapouidugnatoscingebeli@protonmail.com
description: Reconstructed Celto-Illyrian Religious Practice. 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://sapouidugnatos.github.io/senobessus-dexoares/"
twitter_username: sapouidugnatos
github_username:  sapouidugnatos

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
host: 0.0.0.0
sass:
    sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
